// Turns measured eval runs into COST.md's tables. No estimated token counts:
// it refuses to run until both LLM evals have been run with a real key.
//   npm run cost:report -w @fpc/api            # print
//   npm run cost:report -w @fpc/api -- --write # also replace the block in COST.md
import { readFileSync, writeFileSync } from 'node:fs';
import { basename, resolve } from 'node:path';
import { config } from '../config.js';
import { REPO_ROOT, latestResult } from './evalCases.js';

type Usage = { inputTokens?: number | undefined; outputTokens?: number | undefined };
const intentFile = latestResult('intent-llm');
const explainFile = latestResult('explain-llm');
if (!intentFile || !explainFile) {
  throw new Error('Run both LLM evals first: `npm run eval:intent` and `npm run eval:explain` (with LLM_API_KEY).');
}
const intent = JSON.parse(readFileSync(intentFile, 'utf8')) as {
  model: string;
  rows: { telemetry: { usage?: Usage } }[];
};
const explainRun = JSON.parse(readFileSync(explainFile, 'utf8')) as {
  model: string;
  summary: { explanations: number; retryOk: number; template: number };
  rows: { attempts: Usage[] }[];
};

const { inputUsdPerMTok: pIn, outputUsdPerMTok: pOut } = config.pricing;
const cost = (u: Usage) => ((u.inputTokens ?? 0) * pIn + (u.outputTokens ?? 0) * pOut) / 1e6;
const mean = (xs: number[]) => xs.reduce((a, b) => a + b, 0) / Math.max(1, xs.length);

const intentUsages = intent.rows.map((r) => r.telemetry.usage).filter((u): u is Usage => !!u);
const explainCalls = explainRun.rows.filter((r) => r.attempts.length > 0);
const explainAttempts = explainCalls.flatMap((r) => r.attempts);

const iIn = mean(intentUsages.map((u) => u.inputTokens ?? 0));
const iOut = mean(intentUsages.map((u) => u.outputTokens ?? 0));
const eIn = mean(explainAttempts.map((u) => u.inputTokens ?? 0));
const eOut = mean(explainAttempts.map((u) => u.outputTokens ?? 0));
const callsPerExplanation = explainAttempts.length / Math.max(1, explainCalls.length);

const cIntent = mean(intentUsages.map(cost));
/** Per explanation request, retries included. */
const cExplain = mean(explainCalls.map((r) => r.attempts.reduce((s, a) => s + cost(a), 0)));
const cRequest = cIntent + cExplain;

const usd = (n: number) => (n >= 1 ? `$${n.toFixed(2)}` : n >= 0.01 ? `$${n.toFixed(3)}` : `$${n.toFixed(5)}`);
const HIT_RATES = [0, 0.5, 0.8];
const VOLUMES = [10_000, 100_000];
const budget = config.abuse.dailyLlmCallBudget;
// A ceiling, not an average: largest input seen (bounded by the 500-char input cap) plus a
// full max_tokens output, for whichever call type is more expensive.
const maxIn = (us: Usage[]) => Math.max(...us.map((u) => u.inputTokens ?? 0));
const worstCall = Math.max(
  cost({ inputTokens: maxIn(intentUsages), outputTokens: config.llm.intentMaxTokens }),
  cost({ inputTokens: maxIn(explainAttempts), outputTokens: config.llm.explainMaxTokens }),
);

const md = `_Generated by \`npm run cost:report\` on ${new Date().toISOString().slice(0, 10)} from
\`${basename(intentFile)}\` (${intentUsages.length} intent calls) and \`${basename(explainFile)}\`
(${explainCalls.length} explanations, ${explainAttempts.length} calls). Model: \`${intent.model}\`.
Prices: $${pIn} / $${pOut} per MTok input / output._

**Measured tokens per call (mean)**

| Call | Input tokens | Output tokens | Cost per call |
|---|---:|---:|---:|
| #1 intent | ${iIn.toFixed(0)} | ${iOut.toFixed(0)} | ${usd(cIntent)} |
| #2 explanation (per attempt) | ${eIn.toFixed(0)} | ${eOut.toFixed(0)} | ${usd(cost({ inputTokens: eIn, outputTokens: eOut }))} |
| #2 explanation (per request, incl. retries ×${callsPerExplanation.toFixed(2)}) | | | ${usd(cExplain)} |
| **One uncached check (intent + explanation)** | | | **${usd(cRequest)}** |

Guard outcome on this run: ${explainCalls.length - explainRun.summary.retryOk - explainRun.summary.template} passed first try,
${explainRun.summary.retryOk} after retry, ${explainRun.summary.template} fell back to the template.

**Cost by volume and cache-hit rate** (same hit rate assumed for both cache layers)

| Cache hit rate | Per check | 10k checks / day | 100k checks / day | 10k / month (×30) | 100k / month (×30) |
|---|---:|---:|---:|---:|---:|
${HIT_RATES.map((h) => {
  const per = (1 - h) * cRequest;
  return `| ${h * 100}% | ${usd(per)} | ${usd(per * VOLUMES[0]!)} | ${usd(per * VOLUMES[1]!)} | ${usd(per * VOLUMES[0]! * 30)} | ${usd(per * VOLUMES[1]! * 30)} |`;
}).join('\n')}

**Hard ceiling.** The daily LLM call budget is ${budget.toLocaleString('en-US')} calls. A single call can cost at most
${usd(worstCall)} (largest measured input + a full \`max_tokens\` output), so the LLM bill cannot exceed
**${usd(budget * worstCall)} / day**, whatever the traffic. Typical spend at the cap is ${usd(budget * cost({ inputTokens: (iIn + eIn) / 2, outputTokens: (iOut + eOut) / 2 }))} / day.

**Batch precompute.** Pre-writing explanations for the top N queries via the Batch API (50% off):
N = 1,000 → ${usd(1_000 * cExplain * 0.5)}; N = 10,000 → ${usd(10_000 * cExplain * 0.5)} per DATA_VERSION.`;

console.log(md);

if (process.argv.includes('--write')) {
  const path = resolve(REPO_ROOT, 'COST.md');
  const doc = readFileSync(path, 'utf8');
  const re = /(<!-- cost-report:begin -->)[\s\S]*?(<!-- cost-report:end -->)/;
  if (!re.test(doc)) throw new Error('COST.md is missing the cost-report markers');
  writeFileSync(path, doc.replace(re, `$1\n${md}\n$2`));
  console.log(`\nwrote ${path}`);
}
